* Jane Austen and Seth Grahame-Smith (2009): Pride and Prejudice and Zombies - The Classic Regency Romance - Now with Ultraviolent Zombie Mayhem
:PROPERTIES:
:Custom_id: austen09:_pride_prejud_zombies_class_regen
:END:

** The Concept.

The concept is simple, if bonkers.  Take a classic piece of English
Literature, the sort of gentle story telling thousands of students are
made to read every year, and introduce a Zombie apocalypse.

** The Execution.

As someone who *loves* the source book, and has read it many, many
times, I should probably hate this. But it is very well done.  Much of
the content is lifted directly from the source, and the insertions are
well done, matching stylistically the origin.  The additions have been
done by someone who clearly loves the original, but can see a
branched, alternate reality which sits alongside the original and
meets their desire for Zombie slashing fun.

It is also very funny.

** Other Comments.

The book is great. As is almost always the case the film isn't as
good. It isn't awful, but it has to change the ending and, like other
feature length adaptations (see the Aldous Huxley screenplay version
of P&P) it suffers from compression. But the lovely Lilly James is
excellent, and very lovely. She could kick my arse any time!
