* Pete Rawlik (2016): Reanimatrix - An Arkham Romance
:PROPERTIES:
:Custom_id: rawlik16:_reanim_arkham_roman
:END:

An interesting book which takes place in a Lovecraft inspired
world. The central protagonist is Robert Peaslee, who, at the
beginning of the book is working as security for the diplomats working
on the peace agreement at the end of the Great War. Peaslee is in
Paris when he is sent to a villa on the edge of the city.  At the
villa he meets a reanimated corpse who is going through the motions of
their most significant life event.  Peaslee leaves, disturbed and
horrified by his experience, but this is just the start of his descent
into horror and madness.

The story arc initially follows the experiences that Peaslee has where
he meets various mad scientists and their creations and creatures from
beyond our ken. These eventually bring Peaslee into contact with a
murder case, and the body of Megan Halsey-Griffith.

The story is told through a series of diary entries both from the
view of Peaslee, and also from Megan.

I enjoyed this book so much that when I started reading it a second
time by mistake I kept going!  The author's writing is engaging, and
he clearly understands the Lovecraft genre, and manages to express it
well, which isn't always easy.

There is one chapter about a sea voyage which I am sure is lifted very
much from Dracula, I will check this out one day...
